name: Build and Deploy to Github Pages

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  
  workflow_dispatch:

permissions:
  contents: write
  pages: write
  id-token: write
    
concurrency:
      group: "pages"
      cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v3      
      - name: Install .Net
        uses: actions/setup-dotnet@v1
        with: 
          dotnet-version: 7.x
      - name: build
        run: |
          dotnet workload install wasm-tools
          dotnet workload restore
          dotnet publish LP.Plotter/LP.Plotter.csproj -c Release -o publish -nologo

      - uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: publish/wwwroot